# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Nightly All Combinations

on:
  schedule:
    - cron:  '0 2 * * *'
  workflow_dispatch:

jobs:
  build:
    if: github.repository_owner == 'camunda-community-hub' # Don't trigger nightly builds on forks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['11', '16'] #Support LTS releases 8 and 11 and the latest release supported by Micronaut. Note: JDK 8 is not covered here because it would require org.gradle.jvmargs not to be set making the configuration more complex - however JDK 8 is already fully covered in the continuous-integration.yml
        runtime: ['netty', 'jetty', 'tomcat', 'undertow']
        jdk_java_options: ['']
        include:
          - java: '16' # special configuration for Tomcat on JDK 16, see #296
            runtime: 'tomcat'
            jdk_java_options: '--add-opens=java.base/java.io=ALL-UNNAMED'
        exclude:
          - java: '16'
            runtime: 'tomcat'
            jdk_java_options: ''
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Set up JDKs with Matrix Build
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - name: Build with Gradle Wrapper
        run: ./gradlew build --warning-mode=fail -Pmicronaut.runtime=${{ matrix.runtime }} -Dorg.gradle.jvmargs=--illegal-access=permit
        env:
          JDK_JAVA_OPTIONS: ${{ matrix.jdk_java_options }}
