# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Nightly All Combinations

on:
  schedule:
    - cron:  '0 2 * * *'
  workflow_dispatch:

jobs:
  build:
    if: github.repository_owner == 'camunda-community-hub' # Don't trigger nightly builds on forks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['17'] #Support LTS releases 17 and the latest release supported by Micronaut.
        runtime: ['netty', 'jetty', 'tomcat', 'undertow']

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Set up JDKs with Matrix Build
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: 'gradle'
      - name: Set JDK_JAVA_OPTIONS for combination JDK 17/Tomcat #see issue #296
        if: ${{ matrix.java == '17' && matrix.runtime == 'tomcat' }}
        run: echo "JDK_JAVA_OPTIONS='--add-opens=java.base/java.io=ALL-UNNAMED'" >> $GITHUB_ENV
      - name: Build with Gradle Wrapper
        run: ./gradlew build --warning-mode=all -Pmicronaut.runtime=${{ matrix.runtime }} # value 'fail' would be better but the build even this breaks: "mn create-app mytest && cd mytest && ./gradlew clean build --warning-mode fail"
